version: "3"

services:
    # nginx:
    #     container_name: nginx
    #     ports:
    #       - 443:443
    #     build:
    #         context: requirements/nginx
    #     volumes:
    #       - /Users/hyun-zhe/data/wordpress:/usr/share/nginx/wordpress
    # wordpress:
    #     container_name: wordpress
    #     build:
    #         context: requirements/wordpress
    #     volumes:
    #       - /Users/hyun-zhe/data/wordpress:/usr/share/wordpress
    mariadb:
        container_name: mariadb
        build:
            context: requirements/mariadb
        env_file:
          - .env
        volumes:
          - /Users/hyun-zhe/data/mariadb:/usr/share/mariadb