version: "3"

services:
    nginx:
        image: nginx:buster
        ports:
          - 443:443
        build:
            context: requirements/nginx
        volumes:
          - /Users/hyun-zhe/data/wordpress:/usr/share/nginx/wordpress
    wordpress:
        image: wordpress:buster
        build:
            context: requirements/wordpress
        volumes:
          - /Users/hyun-zhe/data/wordpress:/usr/share/wordpress