version: "3"

services:
    nginx:
        container_name: nginx
        build: ./requirements/nginx
        image: nginx:inception
        depends_on:
          - wordpress
        restart: on-failure
        volumes:
          - website:/var/www/html
        ports:
          - "80:80"
          - "443:443"
        networks:
          - inception

    wordpress:
        container_name: wordpress
        build: ./requirements/wordpress
        image: wordpress:inception
        depends_on:
          - mariadb
          - redis
        restart: on-failure
        env_file:
          - .env
        volumes:
          - website:/var/www/html
        expose:
          - "9000"
        networks:
          - inception

    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb
        image: mariadb:inception
        restart: on-failure
        env_file:
          - .env
        volumes:
          - database:/var/lib/mysql
        expose:
          - "3306"
        networks:
          - inception

    redis:
        container_name: redis
        build: ./requirements/bonus/redis
        image: redis:inception
        restart: on-failure
        expose:
          - "6379"
        networks:
          - inception

    ftp:
        container_name: ftp
        build: ./requirements/bonus/ftp
        image: ftp:inception
        restart: on-failure
        env_file:
          - .env
        volumes:
          - website:/var/www/html
        ports:
          - "20:20"
          - "21:21"
          - "42000-42042:42000-42042"
        networks:
          - inception

    static:
        container_name: static
        build: ./requirements/bonus/static
        image: static:inception
        restart: on-failure
        ports:
          - "4242:4242"
        networks:
          - inception

    adminer:
        container_name: adminer
        build: ./requirements/bonus/adminer
        image: adminer:inception
        depends_on:
          - mariadb
        restart: on-failure
        ports:
          - "8080:8080"
        networks:
          - inception

    compose_ui:
        container_name: compose_ui
        image: francescou/docker-compose-ui:1.13.0
        restart: on-failure
        working_dir: /inception
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - ${PWD}:/inception
        ports:
          - "5000:5000"

volumes:
    database:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${HOME}/data/mariadb
    website:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${HOME}/data/wordpress

networks:
    inception:
        driver: bridge